name: ZombieBoss
main: ZombieBoss\\Main
version: 1.1.0
api: 5.0.0
author: ChatGPT
description: Summon a challenging and fully configurable zombie boss
commands:
  spawnboss:
    description: Spawn the zombie boss
    usage: /spawnboss
    permission: zombieboss.command.spawnboss
  zbreload:
    description: Reload ZombieBoss configuration
    usage: /zbreload
    permission: zombieboss.command.reload
permissions:
  zombieboss.command.spawnboss:
    default: op
  zombieboss.command.reload:
    default: op
